apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRESQL_DATABASE: keycloak
  POSTGRESQL_USER: admin
  POSTGRESQL_PASSWORD: '123123'
  # POSTGRESQL_ADMIN_PASSWORD: '123123'