kind: Deployment
apiVersion: apps/v1
metadata: 
  name: keycloak
spec: 
  selector: 
    matchLabels: 
      app: keycloak
  replicas: 1
  strategy: 
    type: "RollingUpdate"
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template: 
    metadata: 
      labels: 
        app: keycloak
    spec: 
      containers: 
        - name: keycloak
          image: "quay.io/keycloak/keycloak:8.0.2"
          imagePullPolicy: "Always"
          env: 
            - name: "KEYCLOAK_USER"
              value: "admin"
            - name: "KEYCLOAK_PASSWORD"
              value: "admin"
            - name: "PROXY_ADDRESS_FORWARDING"
              value: "true"
            - name: "KEYCLOAK_FRONTEND_URL"
              value: "https://http://keycloak-luan-figure-out.apps.os.aws.ubitec.io/auth/"
            - name: "KEYCLOAK_ADMIN_URL"
              value: "https://http://keycloak-luan-figure-out.apps.os.aws.ubitec.io/auth/realms/master/admin/"
          resources:
            requests:
              memory: 0
              cpu: 0
            limits:
              memory: 1024Mi
              cpu: 100m
          ports: 
            # - name: "http"
            #   containerPort: 8080
            - name: "https"
              containerPort: 8080
          readinessProbe:
              httpGet:
                path: "/auth/realms/master"
                port: 8080
